/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ConnectAgentRouteImport } from './routes/connect-agent'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as ProductRouteImport } from './routes/product'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppDemandGraphRouteImport } from './routes/app.demand-graph'
import { Route as AppEvidenceRouteImport } from './routes/app.evidence'
import { Route as AppRecentRouteImport } from './routes/app.recent'
import { Route as AppSupplyRouteImport } from './routes/app.supply'
import { Route as AppOpportunitiesIdRouteImport } from './routes/app.opportunities.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectAgentRoute = ConnectAgentRouteImport.update({
  id: '/connect-agent',
  path: '/connect-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDemandGraphRoute = AppDemandGraphRouteImport.update({
  id: '/demand-graph',
  path: '/demand-graph',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceRoute = AppEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppRoute,
} as any)
const AppRecentRoute = AppRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => AppRoute,
} as any)
const AppSupplyRoute = AppSupplyRouteImport.update({
  id: '/supply',
  path: '/supply',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesIdRoute = AppOpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/connect-agent': typeof ConnectAgentRoute
  '/how-it-works': typeof HowItWorksRoute
  '/network': typeof NetworkRoute
  '/product': typeof ProductRoute
  '/trust': typeof TrustRoute
  '/app/demand-graph': typeof AppDemandGraphRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/recent': typeof AppRecentRoute
  '/app/supply': typeof AppSupplyRoute
  '/app/': typeof AppIndexRoute
  '/app/opportunities/$id': typeof AppOpportunitiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect-agent': typeof ConnectAgentRoute
  '/how-it-works': typeof HowItWorksRoute
  '/network': typeof NetworkRoute
  '/product': typeof ProductRoute
  '/trust': typeof TrustRoute
  '/app/demand-graph': typeof AppDemandGraphRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/recent': typeof AppRecentRoute
  '/app/supply': typeof AppSupplyRoute
  '/app': typeof AppIndexRoute
  '/app/opportunities/$id': typeof AppOpportunitiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/connect-agent': typeof ConnectAgentRoute
  '/how-it-works': typeof HowItWorksRoute
  '/network': typeof NetworkRoute
  '/product': typeof ProductRoute
  '/trust': typeof TrustRoute
  '/app/demand-graph': typeof AppDemandGraphRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/recent': typeof AppRecentRoute
  '/app/supply': typeof AppSupplyRoute
  '/app/': typeof AppIndexRoute
  '/app/opportunities/$id': typeof AppOpportunitiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/connect-agent'
    | '/how-it-works'
    | '/network'
    | '/product'
    | '/trust'
    | '/app/demand-graph'
    | '/app/evidence'
    | '/app/recent'
    | '/app/supply'
    | '/app/'
    | '/app/opportunities/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect-agent'
    | '/how-it-works'
    | '/network'
    | '/product'
    | '/trust'
    | '/app/demand-graph'
    | '/app/evidence'
    | '/app/recent'
    | '/app/supply'
    | '/app'
    | '/app/opportunities/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/connect-agent'
    | '/how-it-works'
    | '/network'
    | '/product'
    | '/trust'
    | '/app/demand-graph'
    | '/app/evidence'
    | '/app/recent'
    | '/app/supply'
    | '/app/'
    | '/app/opportunities/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ConnectAgentRoute: typeof ConnectAgentRoute
  HowItWorksRoute: typeof HowItWorksRoute
  NetworkRoute: typeof NetworkRoute
  ProductRoute: typeof ProductRoute
  TrustRoute: typeof TrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-agent': {
      id: '/connect-agent'
      path: '/connect-agent'
      fullPath: '/connect-agent'
      preLoaderRoute: typeof ConnectAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/demand-graph': {
      id: '/app/demand-graph'
      path: '/demand-graph'
      fullPath: '/app/demand-graph'
      preLoaderRoute: typeof AppDemandGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evidence': {
      id: '/app/evidence'
      path: '/evidence'
      fullPath: '/app/evidence'
      preLoaderRoute: typeof AppEvidenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recent': {
      id: '/app/recent'
      path: '/recent'
      fullPath: '/app/recent'
      preLoaderRoute: typeof AppRecentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/supply': {
      id: '/app/supply'
      path: '/supply'
      fullPath: '/app/supply'
      preLoaderRoute: typeof AppSupplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/opportunities/$id': {
      id: '/app/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/app/opportunities/$id'
      preLoaderRoute: typeof AppOpportunitiesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDemandGraphRoute: typeof AppDemandGraphRoute
  AppEvidenceRoute: typeof AppEvidenceRoute
  AppRecentRoute: typeof AppRecentRoute
  AppSupplyRoute: typeof AppSupplyRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOpportunitiesIdRoute: typeof AppOpportunitiesIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDemandGraphRoute: AppDemandGraphRoute,
  AppEvidenceRoute: AppEvidenceRoute,
  AppRecentRoute: AppRecentRoute,
  AppSupplyRoute: AppSupplyRoute,
  AppIndexRoute: AppIndexRoute,
  AppOpportunitiesIdRoute: AppOpportunitiesIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ConnectAgentRoute: ConnectAgentRoute,
  HowItWorksRoute: HowItWorksRoute,
  NetworkRoute: NetworkRoute,
  ProductRoute: ProductRoute,
  TrustRoute: TrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
